//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dasuFinal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dasuFinal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1073889 {
            get {
                object obj = ResourceManager.GetObject("1073889", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1353543 {
            get {
                object obj = ResourceManager.GetObject("1353543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1431f7159b74218a14ee2141d13433dd {
            get {
                object obj = ResourceManager.GetObject("1431f7159b74218a14ee2141d13433dd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20210413_100004 {
            get {
                object obj = ResourceManager.GetObject("20210413_100004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20210413_135500 {
            get {
                object obj = ResourceManager.GetObject("20210413_135500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _344959 {
            get {
                object obj = ResourceManager.GetObject("344959", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449591 {
            get {
                object obj = ResourceManager.GetObject("3449591", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449592 {
            get {
                object obj = ResourceManager.GetObject("3449592", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449593 {
            get {
                object obj = ResourceManager.GetObject("3449593", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449594 {
            get {
                object obj = ResourceManager.GetObject("3449594", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449595 {
            get {
                object obj = ResourceManager.GetObject("3449595", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3449596 {
            get {
                object obj = ResourceManager.GetObject("3449596", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee480904 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee480904", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809041 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809042 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809042", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809043 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809043", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809044 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809045 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809045", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6ecd3cf0b372fa36f71b486dee4809046 {
            get {
                object obj = ResourceManager.GetObject("6ecd3cf0b372fa36f71b486dee4809046", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_22162286 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-22162286", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622861 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622861", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622862 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622862", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622863 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622863", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622864 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622864", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622865 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622865", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_exam_221622866 {
            get {
                object obj = ResourceManager.GetObject("cartoon-exam-221622866", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_137283719 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-137283719", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_1372837191 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-1372837191", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_1372837192 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-1372837192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_1372837193 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-1372837193", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_1372837194 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-1372837194", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cartoon_happy_kids_playing_together_cartoon_happy_kids_playing_together_holding_hand_kids_1372837195 {
            get {
                object obj = ResourceManager.GetObject("cartoon-happy-kids-playing-together-cartoon-happy-kids-playing-together-holding-h" +
                        "and-kids-1372837195", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_3742531_stock_photo_blank_frame_with_various_kids {
            get {
                object obj = ResourceManager.GetObject("depositphotos_3742531-stock-photo-blank-frame-with-various-kids", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_metal_plate_background {
            get {
                object obj = ResourceManager.GetObject("gold-metal-plate-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_metal_plate_background1 {
            get {
                object obj = ResourceManager.GetObject("gold-metal-plate-background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_metal_plate_background2 {
            get {
                object obj = ResourceManager.GetObject("gold-metal-plate-background2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_metal_plate_background3 {
            get {
                object obj = ResourceManager.GetObject("gold-metal-plate-background3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gold_metal_plate_background4 {
            get {
                object obj = ResourceManager.GetObject("gold-metal-plate-background4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap page_1 {
            get {
                object obj = ResourceManager.GetObject("page_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_simple_music_kid_listening_to_music_dancing_poster_image_199117 {
            get {
                object obj = ResourceManager.GetObject("pngtree-simple-music-kid-listening-to-music-dancing-poster-image_199117", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Set_Of_3_Blue_Green_Prefect_Coastal_Guardian {
            get {
                object obj = ResourceManager.GetObject("Set-Of-3-Blue-Green-Prefect-Coastal-Guardian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
